project/eventmanager/urls.py
from django.urls import path
from eventmanager.views import create_event, landing_page, manage_event, edit_participant, checkin

app_name = 'eventmanager'
urlpatterns = [
    path('', landing_page.landing_page, name='landing_page'),
    path('dashboard', landing_page.dashboard, name='dashboard'),
    path('create', create_event.create_event, name='create_event'),
    path('manage/all_events', manage_event.list_all_events, name='list_all_events'),
    path('manage/<int:event_id>', manage_event.manage_event, name='manage_event'),
    # path('manage/<int:event_id>/<int:participant_id>', views.manage_participants, name='manage_participants'),
    path('manage/participant/<int:participant_id>', edit_participant.edit_participant, name='edit_participant'),
    path('checkin/<int:event_id>/<int:participant_id>/', checkin.checkin, name='checkin'),
    path('cancel_checkin/<int:event_id>/<int:participant_id>', checkin.cancel_checkin, name="cancel_checkin"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('eventmanager.urls')),
]

project/eventmanager/models/event.py
from django.db import models
from django.db.models.constraints import UniqueConstraint


# Create your models here.

class Event(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateField()

    class Meta:
        constraints = [
            UniqueConstraint(fields=['name', 'date'], name='unique_event'), 
        ]
    
    def __str__(self):
        return f"{self.name} on {self.date}"

    def count_registrations(self):
        """
        Returns the amount of people that are signed up
        """
        return self.registration_set.count()

    def count_participants(self):
        """
        Returns the amount of people that are checked in
        """
        #return self.registration_set.filter(checked_in_at__isnull=True).count()
        return self.registration_set.checked_in().count()

project/eventmanager/models/participant.py
from django.db import models
from django.db.models.constraints import UniqueConstraint


# Create your models here.

class Participant(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    organisation = models.CharField(max_length=100, blank=True)
    position = models.CharField(max_length = 100, blank=True)
    email = models.EmailField(max_length=250)
    phone_number = models.CharField(max_length=15, blank=True)
    comment = models.TextField(blank=True)

    class Meta:
        constraints = [
            UniqueConstraint(fields=['first_name', 'last_name', 'email'], name='unique_participant'),
        ]

project/eventmanager/models/registration.py
from django.db import models
from django.db.models.constraints import UniqueConstraint
from django.utils import timezone

class RegistrationQuerySet(models.QuerySet):
    def checked_in(self):
        """
        Filters for registrations of people that have been checked in.
        """
        return self.filter(checked_in_at__isnull=False)

class Registration(models.Model):
    participant = models.ForeignKey('Participant', on_delete=models.CASCADE)
    event = models.ForeignKey('Event', on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    checked_in_at = models.DateTimeField(null=True, blank=True)

    objects = RegistrationQuerySet.as_manager()

    class Meta:
        constraints = [
            UniqueConstraint(fields=['participant', 'event'], name='unique_registration'), 
        ]

project/eventmanager/views.py
from django import forms
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.forms import ModelForm
from eventmanager.models import Event, Participant, Registration
import csv
import io


# Create your views here.

def landing_page(request):
    context = {}
    return render(request, 'eventmanager/landing_page.html', context)

def create_event(request):
    class EventForm(ModelForm):
        class Meta:
            model = Event
            fields = ['name', 'date']

    # If the form was sent:
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save()
            return HttpResponseRedirect(reverse('eventmanager:manage_event', args=[event.id]))

    # If the site is called for the first time:
    else:
        form = EventForm()
    return render(request, 'eventmanager/create_event.html', {'form': form})

def handle_participant_csv_upload(event, djangoStyleFile):
    uploaded_file_as_bytes = djangoStyleFile.read()
    uploaded_file_as_a_string = uploaded_file_as_bytes.decode(djangoStyleFile.charset or 'utf-8')
    file = io.StringIO(uploaded_file_as_a_string)
    reader = csv.DictReader(file)
    for row in reader:
        #TODO: VALIDATE ROW INFO
        participant = get_or_create_participant(row)
        get_or_create_registration(participant, event)
        print(row)

def get_or_create_participant(data:dict):
    email = data['email'].lower()
    try: 
        p = Participant.objects.filter(email=email).get()
        # TODO: How do I update fields of P that haven't been filled before
        # without going through each manually?
    except Participant.DoesNotExist:
        p = Participant(**data)
        p.full_clean()
        p.save()
    return p

def get_or_create_registration(participant, event):
    try:
        rego = participant.registration_set.filter(event=event).get()
    except Registration.DoesNotExist:
        rego = Registration(participant=participant, event=event)
        rego.full_clean()
        rego.save()
    return

def manage_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    class UploadFileForm(forms.Form):
        file = forms.FileField()

    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_participant_csv_upload(event, request.FILES['file'])
            print(request.FILES)
            return HttpResponse('Upload was successful')
    else:
        form = UploadFileForm()
    return render(request, 'eventmanager/manage_event.html', {'event':event, 'form':form})



# Still needs EVERYTHING DONE (even create .html page)

def manage_participants(request, event_id):
    response = f"You are managing the participants of event {event_id}"
    return HttpResponse(response)

def edit_participant(request, participant_id):
    response = f"You are managing participant no {participant_id}"
    return HttpResponse(response)

def checkin(request, event_id, participant_id):
    response = f"You have checked in {participant_id}"
    return HttpResponse(response)

project/eventmanager/views/checkin.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.forms import ModelForm
from eventmanager.models import Event, Participant, Registration
from datetime import datetime
from django.contrib.auth.decorators import login_required

# The ORM

def registration(event, participant):
    try:
        rego = Registration.objects.filter(participant=participant, event=event).get()
        if not rego.checked_in_at:
            now = datetime.now()
            rego.checked_in_at = now
            rego.full_clean()
            rego.save()
            return f"Success: Registration for {participant.first_name} {participant.last_name} for {event.name} was successful"
        else:
            return f"{participant.first_name} {participant.last_name} already checked in for {event.name} on {rego.checked_in_at}"
    except Registration.DoesNotExist:
        return "Error: Participant is not registered for this event"

def cancel_checked_in_at(event, participant):
    try:
        rego = Registration.objects.filter(participant=participant, event=event).get()
        if not rego.checked_in_at:
            return "Alert: Participant is not checked in"
        else:
            rego.checked_in_at = None
            rego.full_clean()
            rego.save()
            return "Success: Participant's checkin was cancelled"
    except Registration.DoesNotExist:
        # Participant is not registered for this event
        return "Error"

# The Views 

@login_required
def checkin(request, event_id, participant_id):
    event = get_object_or_404(Event, pk=event_id)
    participant = get_object_or_404(Participant, pk=participant_id)

    msg = registration(event, participant)

    context = {
        'event': event,
        'p': participant,
        'msg': msg
    }
    return render(request, 'eventmanager/checkin.html', context)


@login_required
def cancel_checkin(request, event_id, participant_id):
    event = get_object_or_404(Event, pk=event_id)
    participant = get_object_or_404(Participant, pk=participant_id)

    msg = cancel_checked_in_at(event, participant)

    if msg == "Error":
        output = "Participant is not registered for this event. Something went wrong"
        return HttpResponse(output)
    else:
        return HttpResponseRedirect(reverse('eventmanager:manage_event', args=[event_id]))

project/eventmanager/views/create_event.py
from django import forms
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.forms import ModelForm
from eventmanager.models import Event, Participant, Registration
import csv
import io
from django.contrib.auth.decorators import login_required

@login_required
def create_event(request):
    class EventForm(ModelForm):
        class Meta:
            model = Event
            fields = ['name', 'date']
            widgets = {
                'name': forms.TextInput(attrs={'placeholder': 'Event Name'}),
                'date': forms.DateInput(attrs={'type': 'date'}),
            }

    # If the form was sent:
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save()
            return HttpResponseRedirect(reverse('eventmanager:manage_event', args=[event.id]))

    # If the site is called for the first time:
    else:
        form = EventForm()
    return render(request, 'eventmanager/create_event.html', {'form': form})

project/eventmanager/views/edit_participant.py
from django import forms
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.forms import ModelForm
from eventmanager.models import Event, Participant, Registration
import csv
import io
from django.contrib.auth.decorators import login_required

@login_required
def edit_participant(request, participant_id):
    response = f"You are managing participant no {participant_id}"
    return HttpResponse(response)

project/eventmanager/views/landing_page.py
from django import forms
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.forms import ModelForm
from eventmanager.models import Event, Participant, Registration
import csv
import io
from django.contrib.auth.decorators import login_required


def landing_page(request):
    context = {}
    return render(request, 'eventmanager/landing_page.html', context)


@login_required
def dashboard(request):
    latest_event_list = Event.objects.order_by('-date')[:10]
    context = {
        'latest_event_list': latest_event_list,
    }
    return render(request, 'eventmanager/dashboard.html', context)

project/eventmanager/views/manage_event.py
from django import forms
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404
from eventmanager.models import Event, Participant, Registration
from django.http import HttpResponse
import csv
import io
from django.contrib.auth.decorators import login_required

# TODO: Create QR code list for download 


# FUNCTIONS HANDLING ORM

def handle_participant_csv_upload(event, djangoStyleFile):
    error_msg = []

    uploaded_file_as_bytes = djangoStyleFile.read()
    uploaded_file_as_a_string = uploaded_file_as_bytes.decode(djangoStyleFile.charset or 'utf-8')
    file = io.StringIO(uploaded_file_as_a_string)
    reader = csv.DictReader(file)

    for row_nr, row in enumerate(reader, start=2):
        # Step One: Clean and verify file info
        cleaned_row = validate_row(row)
        missing_fieldname = is_fieldname_missing(cleaned_row)
        if missing_fieldname:
            error_msg = [f"ERROR: The column(s) {missing_fieldname} are missing. Please add them to your file and try again"]
            break
        
        # Step Two: Update Database
        try:
            participant = get_or_create_participant(cleaned_row)
            get_or_create_registration(participant, event)
        except ValidationError as e:
            error_msg.append(f"In Row {row_nr}: {e}")
            continue
        print(row)

    return error_msg


PARTICIPANT_LIST_FIELDNAMES = {'organisation', 'first_name', 'last_name', 'position', 'email', 'phone_number', 'comment'}

def validate_row(row):
    cleaned_row = {}
    for k, v in row.items():
        v = v.strip()
        if k in PARTICIPANT_LIST_FIELDNAMES:
            if k == 'email':
                cleaned_row[k] = v.lower()
            elif k == 'comment':
                cleaned_row[k] = v
            else:
                cleaned_row[k] = v.title()
    return cleaned_row

def is_fieldname_missing(cleaned_row):
    """
    Compares set PARTICIPANT_LIST_FIELDNAME against keys in participant_dictionary.
    If the same returns empty list, else returns missing fieldname
    """
    key_list = set(cleaned_row)
    missing = PARTICIPANT_LIST_FIELDNAMES.difference(key_list)
    return missing

def get_or_create_participant(data:dict):
    email = data['email']
    first_name = data['first_name']
    last_name = data['last_name']

    try: 
        p = Participant.objects.filter(email=email, first_name=first_name, last_name=last_name).get()
    except Participant.DoesNotExist:
        p = Participant(**data)
        p.full_clean()
        p.save()
    else:
        for k, v in data.items():
            # Set field "k" on Participant to be value "v".
            setattr(p, k, v)
        p.full_clean()
        p.save()
    return p


def get_or_create_registration(participant, event):
    try:
        rego = participant.registration_set.filter(event=event).get()
    except Registration.DoesNotExist:
        rego = Registration(participant=participant, event=event)
        rego.full_clean()
        rego.save()
    return


# ACTUAL SITE VIEW

@login_required
def manage_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    has_been_uploaded = False
    error_msg = ""

    class UploadFileForm(forms.Form):
        file = forms.FileField()

    if request.method == "POST":
        has_been_uploaded = True
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            error_msg = handle_participant_csv_upload(event, request.FILES['file'])
            # return HttpResponse('Upload was successful')
    else:
        form = UploadFileForm()

    registration_query = Registration.objects.filter(event=event_id).order_by('participant__first_name', 'participant__last_name')  # returns registration list

    context = {
        'event': event, 
        'form': form, 
        'registration_list': registration_query,
        'has_been_uploaded': has_been_uploaded,  # shows if site was loaded for the first time
        'error_msg': error_msg,
    }

    return render(request, 'eventmanager/manage_event.html', context)


@login_required
def list_all_events(request):
    event_list = Event.objects.order_by('date')
    context = {
        'event_list': event_list
    }

    return render(request, 'eventmanager/list_all_events.html', context)


"""
NEW STUFF:
    #getattr(object, 'attribute') -> value
    #setattr(object, 'atttribute', 'value')
    #hasattr(object, 'attribute_name') -> bool  # Does the given object have an attribute called attribute_name


def my_function(a, b, *args, **kwargs):
    print(a, b, args, kwargs)

my_function(1, 2)  # 1, 2, [], {}
my_function(1, 2, 4, 5, cat='meow', dog='woof')  # 1, 2, [4, 5], {'cat': 'meow', 'dog': 'woof'}
my_function(cat='meow', b=4, chicken='cluck', dog='woof', a=5)  # 5, 4, [], {'...'}
my_function(**{'cat': 'meow', 'dog': 'woof', 'a': 6, 'b': 8})  # a, b, [], {'cat': 'meow', 'dog': 'woof'}
"""

project/eventmanager/templates/eventmanager/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

         <!-- Bootstrap 4 CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        {% block extra_css %}{% endblock %}

        <!-- Pagetitle -->
        <title>{% block page_title %}Mirjam's Eventmanager{% endblock %}</title>

        <!-- Stylesheets here -->
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'eventmanager:dashboard' %}">Home</a>
              <!-- Navbar Hamburger Menu for later?
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              -->
            {% if user.is_authenticated %}
              <a class="btn btn-dark btn-outline-light" role="button" href="{% url 'logout' %}">Logout</a>
            {% endif %}
            </div>
        </nav>
        
        <div class="container-fluid mt-4">
        {% block content %}
        
        {% endblock %}
        </div>

        <!-- Option 1: Bootstrap 4 Bundle with Popper -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>    </body>
</html>

project/eventmanager/templates/eventmanager/checkin.html
{% extends "eventmanager/base.html" %}

{% block content %}
    <h1>
        {{ msg }}
    </h1>
    <a href="{% url 'eventmanager:manage_event' event.id %}">Back to manage event</a>
    <!-- JavaScript -->
{% endblock %}

project/eventmanager/templates/eventmanager/create_event.html
{% extends "eventmanager/base.html" %}

<!-- Imports Cripsy for Form Styling -->
{% load crispy_forms_tags %}

{% block content %}
    <h1 class="text-center mb-4">Create a new event</h1>

    <div class="text-center col-12 col-md-6 offset-md-3">
    <form action="{% url 'eventmanager:create_event' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-warning" type="submit" value="Submit">
    </form>
    </div>

    <!-- JavaScript -->
{% endblock %}

project/eventmanager/templates/eventmanager/dashboard.html
{% extends "eventmanager/base.html" %}
{% load static %} {# THIS NEEDS TO BE IN EVERY HTML FILE (that uses the static command)#}

{% block content %}
    <main role="main" class="inner cover text-center">
        <h1 class="cover-heading">Welcome to Miri's Eventmanager!</h1>

        <h4 class="lead">Choose one of the options below:</h4>

        <div class="row lead my-4">
            <div class="col-12 col-md-3 offset-md-3">
                <a class="btn btn-lg btn-info btn-block" role="button" href="{% url 'eventmanager:create_event' %}">Create New Event</a> <br>
            </div>
            <div class="col-12 col-md-3">
                <button class="btn btn-lg btn-warning btn-block" type="button" data-toggle="collapse" data-target="#previousEvents" aria-expanded="false" aria-controls="previousEvents">
                    Manage Existing Events
                </button>
            </div>
        </div>

        <main role="main" class="collapse inner cover text-center" id="previousEvents">
            <div class="mb-4">
                <h4>Choose an existing event:</h4>
            </div>

            <div class="table-responsive">
                <table class="table table-bordered table-hover col-12 col-md-6 offset-md-3">
                    <thead class="thead-light">
                        <th scope="col">Event name</th>
                        <th scope="col">Date</th>
                        <th scope="col">Registrations</th>
                        <th scope="col">Go to event</th>
                    </thead>
                    <tbody>
                        {% for event in latest_event_list %}
                        <tr scope="row">
                            <td>{{ event.name }}</td>
                            <td>{{ event.date }}</td>
                            <td>{{ event.count_registrations }}</td>
                            <td>
                                <a class="btn btn-sm btn-outline-dark" href="{% url 'eventmanager:manage_event' event.id %}">Manage</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div>
                <a href="{% url 'eventmanager:list_all_events' %}" id="allEvents">see all events</a>
            </div>
        </main>
    </main>

    <!-- JavaScript -->
{% endblock %}

project/eventmanager/templates/eventmanager/landing_page.html
{% extends "eventmanager/base.html" %}

{% block content %}
    <div class="text-center">
        <h1 class="mb-4">Welcome to Miri's Eventmanager</h1>
        <a class="btn btn-warning" href="{% url 'eventmanager:dashboard' %}">Go to dashboard</a>
    </div>
    <!-- JavaScript -->
{% endblock %}

project/eventmanager/templates/eventmanager/list_all_events.html
{% extends "eventmanager/base.html" %}

{% block content %}
    <div class="text-center">
        <h1 class="mb-4">All Events by AC Sydney:</h1>
    </div>
    <div>
        <ul class="list-group col-12 col-md-4 offset-md-4 text-center">
            {% for event in event_list %}
                <a class="list-group-item list-group-item-action list-group-item-dark" href="{% url 'eventmanager:manage_event' event.id %}">{{ event }}</a>
            {% endfor %}
        </ul>
    </div>
    <!-- JavaScript -->
{% endblock %}

project/eventmanager/templates/eventmanager/manage_event.html
{% extends "eventmanager/base.html" %}

<!-- Imports Cripsy for Form Styling -->
{% load crispy_forms_tags %}

{% block content %}

<h1 class="text-center">Managing Event "{{ event.name }}" on {{ event.date }}</h1>

{% if has_been_uploaded %}
<div class="py-3">
    {% if error_msg %}
        {% if error_msg|length > 1 %}
            <div class="alert alert-danger" role="alert">
                <h4>The following errors occured:</h4>
                <ul>
                    {% for entry in error_msg %}
                        <li>{{ entry }}</li>
                    {% endfor %}
                </ul>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% else %}
            <div class="alert alert-danger" role="alert">
                {{ error_msg }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
    {% else %}
        <div class="alert alert-success" role="alert">
            Your file has been successfully uploaded
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
</div>
{% endif %}

<div class="text-center">
    <button class="btn btn-warning my-3" type="button" data-toggle="collapse" data-target="#uploadParticipants" aria-expanded="false" aria-controls="collapseExample">
        Upload List of Participants
    </button>
</div>
    <!-- Upload Participant List -->
<div id="uploadParticipants" class="collapse card card-body bg-secondary text-white py-4">
    <form class="mb-3" action="{% url 'eventmanager:manage_event' event.id %}" method="post" enctype="multipart/form-data">
        <p>Upload the participant list as a .csv here.</p>
        {{ form|crispy }}
        <label for="uploadCSV" class="form-label">
            <p class="form-text">(Columns: organisation, first_name, last_name, position, email (must exist), phone_number, comment)</p>
            <input type="submit" value="Submit" id="uploadCSV">
        </label>
        {% csrf_token %}
    </form>
</div>

<!-- Show Current Participant List -->
{% if registration_list %}
<h3 class="py-3 text-center">List of registered participants for this event</h3>
<div class="py-3 text-center">
    <p>Checked-in: {{ event.count_participants }}</p>
</div>
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover">
            <thead class="table-secondary">
                <tr>
                    <th scope="col">organisation</th>
                    <th scope="col">first_name</th>
                    <th scope="col">last_name</th>
                    <th scope="col">position</th>
                    <th scope="col">email</th>
                    <th scope="col">phone_number</th>
                    <th scope="col">comment</th>
                    <th scope="col">created_at</th>
                    <th scope="col">is checked in?</th>
                    <th scope="col">check in</th>
                    <th scope="col">edit</th>
                </tr>
            </thead>
            {% for rego in registration_list %}
                <tr scope="row" {% if rego.checked_in_at %} class="table-success" {% endif %}>
                    <td>{{ rego.participant.organisation }}</td>
                    <td>{{ rego.participant.first_name }}</td>
                    <td>{{ rego.participant.last_name }}</td>
                    <td>{{ rego.participant.position }}</td>
                    <td>{{ rego.participant.email }}</td>
                    <td>{{ rego.participant.phone_number }}</td>
                    <td>{{ rego.participant.comment }}</td>
                    <td>{{ rego.created_at }}</td>
                    <td> {{ rego.checked_in_at }}</td>
                    <td>
                        {% if not rego.checked_in_at %}
                        <a href="{% url 'eventmanager:checkin' event.id rego.participant.id%}">Checkin</a>
                        {% else %}
                        <a href="{% url 'eventmanager:cancel_checkin' event.id rego.participant.id %}">Cancel Checkin</a>
                        {% endif %}
                    </td>
                    <td><a href="{% url 'eventmanager:edit_participant' rego.participant.id %}">Edit</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% else %}
    <p class="text-center my-4">No participants yet registered for this event.</p>
{% endif %}

<!-- JavaScript -->
{% endblock %}